name: Deploy to GitHub Pages

on:
  # رح يشتغل الكود تلقائياً لما تعدل أي شي بفرع main
  push:
    branches: [ main ]
  # بيسمحلك تشغل الكود يدوياً إذا لزم الأمر
  workflow_dispatch:

# إعطاء الصلاحيات اللازمة لجيت هب لرفع الملفات
permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
        
      - name: Install, build, and upload your site
        uses: withastro/action@v3
        with:
          path: .
          node-version: 20
          package-manager: npm

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
